language: python
python:
    - "2.7"

sudo: required

addons:
    apt_packages:
        - python-scipy
        - python-numpy

virtualenv:
    system_site_packages: true

install: "pip install -r requirements.txt"

script: nosetests


