language: python
python:
    - "2.7_with_system_site_packages"

sudo: false

addons:
    apt:
        packages:
        - python-numpy
        - python-scipy

notifications: false

install: "pip install -r requirements.txt"

script: nosetests


